version: '3.8'
services:
  shadowsocks:
    image: ghcr.io/shadowsocks/ssserver-rust
    cap_drop:
    - ALL
    cap_add:
    # Allow changing to the "nobody" user
    - SETUID
    - SETGID
    volumes:
    - ./shadowsocks.json:/etc/shadowsocks-rust/config.json:ro
    ports:
    - 8443:8443
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  tools:
    build:
      context: .
      dockerfile: tools.Dockerfile
    cap_drop:
    - ALL
    # Uncomment the following two lines to allow ping from the tools container
    # cap_add:
    # - NET_RAW
    volumes:
    - ./shadowsocks.json:/etc/shadowsocks-rust/config.json:ro
    env_file:
    - .env
