version: '3.8'
services:
  shadowsocks:
    build:
      context: .
      dockerfile: shadowsocks.Dockerfile
    cap_drop:
    - ALL
    cap_add:
    # Allow changing to the "nobody" user
    - SETUID
    - SETGID
    volumes:
    - ./shadowsocks.json:/etc/shadowsocks-rust/config.json
    ports:
    - 8443:8443
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
