= (WIP) guerrilla — A collection of easy-to-deploy proxies for digital guerrillas
de4thr0ll <github.com/de4thr0ll>
:toc:
:icons: font

This repository provides a Docker Compose project for running different kinds of proxies on your own servers.
More services and documentation will be added later.

== Usage

. Clone the project
+
```console
$ git clone https://github.com/de4thr0ll/guerrilla.git
```
+
NOTE: All further commands are performed in the cloned project root directory.

. Build and pull all container images
+
```console
$ docker compose pull && docker compose build
```
+
NOTE: This may take quite some time, especially for the tools image.

. Add a `.env` file with the following contents
+
```
EXTERNAL_IP=<your.server_ip.without.angles>
```

. Follow further instructions for a specific service or tool.

== Services
=== shadowsocks-rust server
A port of link:https://shadowsocks.org/[shadowsocks] written in Rust. For more, see link:https://github.com/shadowsocks/shadowsocks-rust[this repo].

. Generate a password for the server
+
TIP: See link:#genpass[genpass].

. Create a configuration file
+
```console
$ cp shadowsocks.json{.example,}
```

. Edit the configuration file `shadowsocks.json` as appropriate
+
--
TIP: The config file reference can be found link:https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File[here].

WARNING: If you want to change the port shadowsocks-rust is listening on, don't forget to change it in the `compose.yml` file.

NOTE: The `server` field in the config file must contain the service name, `shadowsocks`.
--

. Start the server
+
```console
$ docker compose up -d shadowsocks
```

== Tools
Miscellaneous tools to simplify your user experience.

=== genqr — Generate a QR code for shadowsocks clients
```console
$ docker compose run tools genqr
```

[#genpass]
=== genpass — Generate a random password using openssl
```console
$ docker compose run tools genpass <size>
```

NOTE: `<size>` is the size of your password in bytes. The password itself will have a larger count of characters since it is encoded in Base64.

TIP: The longer password the better. Make sure to use at least 20-byte passwords.
